Use address finder creating planning applications
unboxed/bops pull request #1733
Opened 2024-04-23 12:50 UTC by cdccollins

### Description of change

- When manually creating planning application, use address finder with OS Places API
- Fill in form using result and get latitude and longitude

### Story Link

https://trello.com/c/LSH77cLG/2831-spike-use-address-to-set-the-position-of-the-red-line-map-when-setting-up-cases-manually

2024-04-23 16:09 UTC, benjamineskola approved these changes

2024-04-23 16:25 UTC, pixeltrix requested changes

2024-04-23 16:25 UTC, pixeltrix commented on app/models/planning_application.rb
> +  end
Can't we do this in a `before_create` rather than running an `UPDATE` right after the `INSERT` ?

2024-04-24 10:12 UTC, pixeltrix approved these changes

2024-04-24 12:31 UTC, merged