Lint govuk_button_link_to
unboxed/bops pull request #1834
Opened 2024-05-29 14:37 UTC by benjamineskola

### Description of change

Extends rubocop check to catch another helper we can make use of.

2024-05-30 09:01 UTC, pixeltrix requested changes

2024-05-30 09:05 UTC, benjamineskola commented on app/components/accordion_sections/application_information_component.html.erb
> +              new_tab: ""
Good catch: most of the places we use new tabs already include the 'opens in new tab' in their text, so I didn't bother adding it anywhere, but it looks like there are a few places that could benefit.

2024-05-30 14:41 UTC, benbaumann95 approved these changes

2024-06-03 10:10 UTC, pixeltrix approved these changes

2024-06-03 10:11 UTC, merged