List and export letter history
unboxed/bops pull request #2035
Opened 2024-11-14 13:53 UTC by benjamineskola

### Description of change

List history of sent letters and allow exporting of text and history

### Story Link

https://trello.com/c/2P00Jmyn/2798-view-a-copy-of-neighbour-letters

### Screenshots

If you have made changes to the frontend please add screenshots

### Decisions [OPTIONAL]

If you had to make any decisions between different ways of doing things, what where they and why?

### Known issues [OPTIONAL]

Things you know need further follow on work but aren't in scope of this issue

1. issue1
2. issue2

### Further testing or sign off required [OPTIONAL]

e.g.

1. product manager to sign off view templates

2024-11-14 15:53 UTC, pixeltrix commented on app/assets/stylesheets/_main.scss
> +  margin: calc(1.5 * 2.54cm);
Any reason not to use `1.5in` ?

2024-11-14 15:59 UTC, pixeltrix requested changes

2024-11-14 15:59 UTC, pixeltrix commented on app/controllers/planning_applications/neighbour_letter_batches_controller.rb
> +        render plain: result.join("\n") + "\n", layout: false
Why not use the CSV library and a ruby template to do this like we do on Petitions:
https://github.com/alphagov/e-petitions/blob/master/app/views/petitions/index.csv.ruby

2024-11-14 15:59 UTC, pixeltrix commented on app/views/planning_applications/neighbour_letter_batches/show.html.erb
> +    <%= @batch.text %>
Is there a reason for the <br> tags and not using <div> wrappers and a govuk-!-margin-* class?

2024-11-19 12:03 UTC, benbaumann95 approved these changes

2024-11-19 14:15 UTC, pixeltrix approved these changes

2024-11-19 14:20 UTC, merged